version: 2
jobs:
  seed:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install AWS cli
          command: |
            sudo pip install awscli
      - run:
          name: ship first definition to s3
          command: make seed
  
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
        
      # run tests!
      - run: 
          name: Run tests
          command: npm test

      - run:
          name: Deploy application
          command: make deploy

      - run:
          name: Run End to End Test
          command: |
            npm run test:e2e
workflows:
  version: 2
  all:
    jobs:
      - build
      - seed:
          requires:
            - build